name: e_commerce
description: "E-Commerce application"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # utility package
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.2.6

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/logos/
  - assets/icons/
  - assets/images/
