// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwzeE4wXzWCjk9rfYq49ICLo5Dg0CNAY',
    appId: '1:600432026259:web:73fc925a0f8db623896366',
    messagingSenderId: '600432026259',
    projectId: 'ecommerceapp-58226',
    authDomain: 'ecommerceapp-58226.firebaseapp.com',
    storageBucket: 'ecommerceapp-58226.appspot.com',
    measurementId: 'G-CD3EK2X8Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JwxpNfEuc3LA2otKUFndXzylV0kVrVk',
    appId: '1:600432026259:android:2cc8bbfcfd9747c9896366',
    messagingSenderId: '600432026259',
    projectId: 'ecommerceapp-58226',
    storageBucket: 'ecommerceapp-58226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA160s_MKisjr1Y46KslzzfQUksP08oAuw',
    appId: '1:600432026259:ios:86cf5bf26af9e748896366',
    messagingSenderId: '600432026259',
    projectId: 'ecommerceapp-58226',
    storageBucket: 'ecommerceapp-58226.appspot.com',
    androidClientId: '600432026259-v36vhj8dgrp0nc4otdefbli2l7ohdufa.apps.googleusercontent.com',
    iosClientId: '600432026259-6b3l8moa5rkm30ak7t33ntdk5fcqs0tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

}