name: e_commerce
description: "E-Commerce application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # utility package
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_gap: ^1.0.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.1

  #Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/icons/payment_methods/
    - assets/images/onboarding/
    - assets/images/static/
    - assets/images/promotion/
    - assets/images/products/
    